import axiosInstance from '@/lib/axios';
import type { AdoptAnimal } from '@/types/adopt';

export const fetchAdoptAnimals = async () => {
    // const { data } = await axiosInstance.get('/adopt');
    const data: AdoptAnimal[] = [
        {
            animalId: 1,
            happenDate: '2025-11-20',
            species: 'DOG',
            breedType: '믹스견',
            birth: '2024(년생)',
            city: '서울특별시',
            town: '강남구',
            sex: 'M',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=1',
            animalType: 'ABANDONED',
        },
        {
            animalId: 2,
            happenDate: '2025-11-18',
            species: 'DOG',
            breedType: '말티즈',
            birth: '2023(년생)',
            city: '서울특별시',
            town: '강서구',
            sex: 'F',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=2',
            animalType: 'ABANDONED',
        },
        {
            animalId: 3,
            happenDate: '2025-11-15',
            species: 'CAT',
            breedType: '코리안숏헤어',
            birth: '2025(60일미만)(년생)',
            city: '경기도',
            town: '성남시',
            sex: 'F',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=3',
            animalType: 'ABANDONED',
        },
        {
            animalId: 4,
            happenDate: '2025-11-10',
            species: 'DOG',
            breedType: '포메라니안',
            birth: '2022(년생)',
            city: '인천광역시',
            town: '남동구',
            sex: 'M',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=4',
            animalType: 'ABANDONED',
        },
        {
            animalId: 5,
            happenDate: '2025-11-08',
            species: 'CAT',
            breedType: '페르시안',
            birth: '2021(년생)',
            city: '부산광역시',
            town: '해운대구',
            sex: 'F',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=5',
            animalType: 'ABANDONED',
        },
        {
            animalId: 6,
            happenDate: '2025-11-05',
            species: 'DOG',
            breedType: '시츄',
            birth: '2020(년생)',
            city: '대전광역시',
            town: '서구',
            sex: 'Q',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=6',
            animalType: 'ABANDONED',
        },
        {
            animalId: 7,
            happenDate: '2025-11-01',
            species: 'DOG',
            breedType: '진돗개',
            birth: '2019(년생)',
            city: '광주광역시',
            town: '북구',
            sex: 'M',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=7',
            animalType: 'ABANDONED',
        },
        {
            animalId: 8,
            happenDate: '2025-10-28',
            species: 'CAT',
            breedType: '러시안블루',
            birth: '2023(년생)',
            city: '대구광역시',
            town: '수성구',
            sex: 'F',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=8',
            animalType: 'ABANDONED',
        },
        {
            animalId: 9,
            happenDate: '2025-10-25',
            species: 'DOG',
            breedType: '비글',
            birth: '2024(년생)',
            city: '울산광역시',
            town: '남구',
            sex: 'M',
            processState: '보호중',
            profile: 'https://placedog.net/500/280?random=9',
            animalType: 'ABANDONED',
        },
    ];
    return data;
};

export const fetchAdoptAnimalsById = async (id: number) => {
    const { data } = await axiosInstance.get(`/adopt/${id}`);
    return data;
};
